cities/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.CityListView.as_view(), name='home'),
    path('detail/<int:pk>/', views.CityDetailView.as_view(), name='detail'),
    path('add/', views.CityCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='delete'),
]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from routes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cities/', include(('cities.urls', 'cities'))),  # 'cities:home or cities:detail
    path('trains/', include(('trains.urls', 'trains'))),
    path('accounts/', include(('accounts.urls', 'accounts'))),
    path('', views.home, name='home'),
    path('find_routes/', views.find_routes, name='find_routes'),
    path('add_route/', views.add_route, name='add_route'),
    path('save_route/', views.save_route, name='save_route'),
    path('list/', views.RouteListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.RouteDetailView.as_view(), name='detail'),
    path('delete/', views.RouteDeleteView.as_view(), name='delete'),
]

routes/models.py
from django.db import models
from cities.models import City

class Route(models.Model):
    name = models.CharField(max_length=50,
                            unique=True,
                            verbose_name='Name of route')
    travel_times = models.PositiveSmallIntegerField(verbose_name='Total travel time')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE,
                                  related_name='route_from_city_set',
                                  verbose_name='From'
                                  )
    to_city = models.ForeignKey('cities.City', on_delete=models.CASCADE,
                                related_name='route_to_city_set',
                                verbose_name='To'
                               )
    trains = models.ManyToManyField('trains.Train', verbose_name='List of trains')

    def __str__(self):
        return f'Route {self.name} from city : {self.from_city}'
    

    class Meta:
        verbose_name = "Route"
        verbose_name_plural = "Routes"
        ordering = ['travel_times']

templates/about.html
{% extends 'base.html' %}

{% block title %}
{{name}}
{% endblock %}

{% block content %}
<h1> {{name}} </h1>
{% endblock %}

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'trains:create' as trains_create_url %}
{% url 'list' as route_list %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">FindRoute</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item {% if request.path == cities_home_url %} acitve {% endif %}">
                <a class="nav-link aria-current="page" href="{% url 'cities:home' %}">Cities</a>
              </li>
              <li class="nav-item {% if request.path == trains_home_url %} acitve {% endif %}">
                <a class="nav-link" href="{% url 'trains:home' %}">Trains</a>
              </li>
              <li class="nav-item {% if request.path == route_list %} active {% endif %}">
                <a class="nav-link" href="{% url 'list' %}">Routes</a>
              </li>
                
              <li class="nav-item dropdown {% if request.path == cities_create_url or request.path == trains_create_url %} active {% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                  Add
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'cities:create' %}">New city</a>
                  <a class="dropdown-item" href="{% url 'trains:create' %}">New train</a>
                </div>
              </li>
              
              <!-- {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
              {% else %}
                
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>
              {% endif %} -->
            </ul>
          </div>
        </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto my-4">
          {% if messages %}
              {% for message in messages %}
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important:
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                  {% else %}
                  <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                  {% endif %}              
              {% endfor %}          
          {% endif %}
        </div>
      </div>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <script>
      // In your Javascript (external .js resource or <script> tag)
      $(document).ready(function() {
          $('.js-example-basic-single').select2();
          $('.js-example-basic-multiple').select2();
      });
    </script>
  </body>
</html>

templates/form.html
<div class="row">
    <div class="col-md-4">     <!--   уменьшаем размер формы -->
        <form action="{{ action }}" method="post"> {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-primary">{{ button }}</button>
        </form> 
    </div>
</div>

templates/home.html
{% extends 'base.html' %}

{% block title %}
hello {{name}}
{% endblock %}

{% block content %}
<h1> hello {{name}} </h1>
{% endblock %}